<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>RandomPlaylistMod</AssemblyName>
    <RootNamespace>RandomPlaylistMod</RootNamespace>
    <Version>1.5.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <PropertyGroup>
    <BeatSaberDir>F:\paly\BSManager\BSInstances\1.40.8</BeatSaberDir>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="IPA.Loader">
      <HintPath>$(BeatSaberDir)\IPA\Data\Managed\IPA.Loader.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\UnityEngine.UI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\UnityEngine.UIModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Main">
      <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\Main.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="BeatSaber.ViewSystem">
      <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\BeatSaber.ViewSystem.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="SiraUtil">
      <HintPath>$(BeatSaberDir)\Plugins\SiraUtil.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="SongCore">
      <HintPath>$(BeatSaberDir)\Plugins\SongCore.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="BSML">
      <HintPath>$(BeatSaberDir)\Plugins\BSML.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="BS_Utils">
      <HintPath>$(BeatSaberDir)\Plugins\BS_Utils.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Zenject">
      <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\Zenject.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Zenject-usage">
      <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\Zenject-usage.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="HMUI">
      <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\HMUI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="VRUI">
      <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\VRUI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(BeatSaberDir)\IPA\Libs\0Harmony.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(BeatSaberDir)\IPA\Libs\Newtonsoft.Json.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="BeatSaberPlaylistsLib">
      <HintPath>$(BeatSaberDir)\Libs\BeatSaberPlaylistsLib.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="DataModels">
      <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\DataModels.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="BeatmapCore">
      <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\BeatmapCore.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Colors">
      <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\Colors.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="GameplayCore">
      <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\GameplayCore.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="BeatSaber.GameSettings">
      <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\BeatSaber.GameSettings.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="BeatSaber.Settings">
      <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\BeatSaber.Settings.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="MenuSystem">
      <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\MenuSystem.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Core">
      <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\Core.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="SongDetailsCache">
      <HintPath>$(BeatSaberDir)\Libs\SongDetailsCache.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\Unity.TextMeshPro.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="manifest.json" />
    <EmbeddedResource Include="UI\Views\RandomPlaylistView.bsml" />
    <EmbeddedResource Include="UI\Views\SessionHudView.bsml" />
  </ItemGroup>
</Project>